### ISSUE TITLE
source_max is broken on returned paths.

### ISSUE THREAD

**Issue by nullstyle** [stellar/go-horizon#239]

**Comment by TbLtzk** [comment]
I'm still getting those results on testnet, so I assume it has not been deployed yet.
When should this go to testnet/livenet respectively?

**Comment by nullstyle** [comment]
Sorry about that @TbLtzk!  It has been deployed to both testnet and livenet now.

**Comment by TbLtzk** [comment]
Thanks @nullstyle, perfect! Sorry to bother you again with a final question: the paths result (see link below) now contains 2 Options for sending 50 XLM:
- 50 XLM direct
- 98 XLM via Asset 'AAA' (and back)

I think it does not make sense to have multiple options with the same source Asset, because I would obviously choose the lower amount. What do you think? And would you consider this be part of horizon or should clients filter if desired?
Example again: https://horizon-testnet.stellar.org/paths?destination_account=GDJXQYEWDPGYK4LGCLFEV6HBIW3M22IK6NN2WQONHP3ELH6HINIKBVY7&source_account=GAN65D2FEI63T4MBMOWWOP3K7VS6SVI5T6NNKIHNCI6PN32IGF6OVKSS&destination_amount=50&destination_asset_type=native

**Comment by nullstyle** [comment]
No worries!  It's not a bother at all @TbLtzk 

The behavior is by design. The simple path finder in horizon is not to be the most efficient, but rather it simply aims to provide useable paths. It's the client's responsibility to filter and find the appropriate/best path given the current path finding implementation.

The system is pluggable, however, and encourage others to build additional implementations (you can see the go interfaces to satisfy here: https://github.com/stellar/horizon/blob/master/src/github.com/stellar/horizon/paths/main.go)

**Comment by nullstyle** [comment]
Furthermore, IMO it's in the client's best interest to decide the best path itself...  your software will perform better because it will have fewer dependencies on externalities to achieve correct behavior.

**Comment by jedmccaleb** [comment]
Hmm idk. I think it should only return 1 path per sending asset. Seems better to make the behavior of this default pathfinder simpler for the client and if people want more complex behavior then they can customize the pathfinder rather than the other way around.
The client would still be able to choose between paths in different assets.

**Comment by nullstyle** [comment]
My concern is that people will start making the same assumption the TbLtzk did.  I can change it, but I believe that picking the best path for a given source asset should be the client libraries responsibility, and I think we're taking a risk around people misinterpreting what will amount to an implicit protocol.

**Comment by jedmccaleb** [comment]
His assumption was that the pathfinder would always find the best one?
Why would the client ever want to pick a worse path? Also for assets with lots of active orderbooks trading them, there could be many many different paths.

**Comment by TbLtzk** [comment]
Even worse: the example above is XLM -> AAA -> XLM which would mean: we get one path per any asset on the entire network that has at least one bid and one ask of sufficient size.
At least we should exclude paths that buy and sell on the same orderbook.
But still I can't think of any use case where I want the more expensive path except the cheaper one does not work for whatever reason, which of course should not happen when it is returned as a valid payment option.

**Comment by nullstyle** [comment]
@jedmccaleb for example, a bank may want to route a payment through it's own forex desk.  That said, you know I don't like to get into the gave of making assumptions when the use case is not clear.  

I'm convinced this is worthy to be considered a bug for our pathfinder.  I'll open up an issue.
