### ISSUE TITLE
Result codes should be the same everywhere

### ISSUE THREAD

**Issue by bartekn** [stellar/go-horizon#253]
Result codes returned by Horizon are different that those in XDR and our docs. For example, trying to send Payment to the account that doesn't exist results in `op_no_destination` code but it's `PAYMENT_NO_DESTINATION` in [XDR](https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-transaction.x#L384) and in [devportal](https://www.stellar.org/developers/learn/concepts/list-of-operations.html#payment). To handle all possible cases properly a developer needs to check the source of Horizon to figure out what are the error codes.

**Comment by nullstyle** [comment]
So, horizon's goal is to make it easier on others to develop client software that integrates with the stellar network.  Given the design and other restrictions regarding our XDR schema, the error messages, IMO, make it harder to integrate with the network.

For example, your example above is technically incorrect.  If you try to send a `PaymentOp` to an account that doesn't exist the error from stellar-core is `PAYMENT_NO_DESTINATION`, but that's not the whole truth.  A `PathPaymentOp` that fails for the same reason fails with `PATH_PAYMENT_NO_DESTINATION`.

To lower the number of flags that a developer must learn, I chose _not_ to mirror the raw xdr errors.  In this case, a developer need not know that the source operation was a path payment, they simply check their errors for "op_no_destination".

I'm happy to discuss this further, but I'm going to close the issue because I don't believe it is cut and dry that we should sync our error codes with the underlying stellar-core errors.   Instead, I believe we should update our documentation to use horizon's presentation of the errors or otherwise make clear the distinction between stellar-core's behavior and horizon's.  We can always repoen the ticket if we decide I'm dumb :)

**Comment by bartekn** [comment]
Makes sense. Created this issue: https://github.com/stellar/horizon/issues/258
