### ISSUE TITLE
Design "All assets" endpoint

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go-horizon#378]
Gives you a list of all the assets that are currently issued in the network. Probably also related to an end point that gives you the total assets outstanding from a particular issuer.

**Comment by nullstyle** [comment]
Notes from our convo about this issue:

- total issued amount of asset
- number of accounts holding asset
- all assets in the system
- asset flags from issuer
- Stellar.toml info 

---

Refresh model:

The assets table will be managed by a system separate from the ingestion system.  It will collect asset information and update a table in horizon that provides summary info for each asset.  Asset summaries will be refreshed as transactions operate with a given asset.  Each ingestion tick should output a list of assets that were seen during ingestion.  The list of changes assets will then be fed into the asset system to refresh the materialized views.

**Comment by tomerweller** [comment]
As a beginning, and to help with this issue: https://github.com/stellar/go/issues/103. Maybe we should start with a simple compact `history_assets table` that will serve as a lookup table, something like this: 

```sql
CREATE TABLE history_assets (
  id SERIAL PRIMARY KEY ,
  asset_type VARCHAR(64) NOT NULL,
  asset_code VARCHAR(12) NOT NULL,
  asset_issuer VARCHAR(56) NOT NULL,
  UNIQUE(asset_type, asset_code, asset_issuer)
);
```

**Comment by nikhilsaraf** [comment]
this will be useful: https://github.com/stellar/go/issues/105

**Comment by nikhilsaraf** [comment]
Here is an initial proposal for the design of the endpoint. I’ve kept it very simple.

### Endpoint
```
GET /assets
```

### URL params
These URL params configure the data returned by the endpoint. We can always add more URL params as filters if we want.
```
amounts: bool - set to true to display the total amount outstanding for the given asset
accounts: bool - set to true to display number of accounts holding the asset
flags: bool - set to true to display the flags set on the issuer account for the asset
toml: bool - set to true to display the stellar.toml file associated with the account
```

### Sample Output for /assets
```javascript
{
    assets: [{
        type: “credit_alphanum4”,
        code: “USD”,
        issuer: “GVDKJJIEJUROISJFLKJDFIDOFUDJFLKDSJFLKF”
    }, {
        type: “credit_alphanum4”,
        code: “BTC”,
        issuer: “GVDKJJIEJUROISJFLKJDFIDOFUDJFLKDSJFLKF”
    }, {
        ...
    }]
}
```

### Sample Output for /assets?amounts=true&accounts=true&flags=true
```javascript
{
    assets: [{
        type: “credit_alphanum4”,
        code: “USD”,
        issuer: “GVDKJJIEJUROISJFLKJDFIDOFUDJFLKDSJFLKF”,
	amount: 100000,
        accounts: 500,
	flags: [AUTHORIZATION REQUIRED, AUTHORIZATION REVOCABLE]
    }, {
        type: “credit_alphanum4”,
        code: “BTC”,
        issuer: “GVDKJJIEJUROISJFLKJDFIDOFUDJFLKDSJFLKF”,
	amount: 3000,
        accounts: 20,
	flags: [AUTHORIZATION REQUIRED, AUTHORIZATION REVOCABLE]
    }, {
        ...
    }]
}
```

We should separate out the Refresh Model into a separate ticket since that’s related to keeping the tables fresh rather than the endpoint. I can follow this comment up with a design for that if you want.

**Comment by tomerweller** [comment]
This is somewhat of a religious argument but I'm not a fan of REST endpoints that return different fields based on the query params.

If all this data is already aggregated and indexed - sending everything at all times is not that expensive.

Also, not in this issue but might be relevant, do we want to be able to filter by issuer or by currency? For example, to get all `USD` assets or all assets by a specific issuer account.

**Comment by nikhilsaraf** [comment]
After discussing offline, we decided that we should have a precomputed table that is separate from the `history_assets` table. We can call this `asset_stats`.

This table will be refreshed on every ingestion tick for only those assets that have changed. Responses will include all the data in the table rather than have output based on the boolean param flags.

This will need a join operation on every query against the `history_assets` table but that should be ok as all other tables using assets would need to do this anyway.

The primary key (ID) for this new table will be the same as the id on the `history_assets` table.
The JSON responses from this API will be in the HAL format for [requests](https://www.stellar.org/developers/horizon/reference/responses.html) and [responses](https://www.stellar.org/developers/horizon/reference/errors.html)
