### ISSUE TITLE
human error code

### ISSUE THREAD

**Issue by FredericHeem** [stellar/go-horizon#48]
A transaction to send lumen from one account to another is sent to go-horizon and it replies with the following message:

{ hash: '22fae4ad6ad65b7a99ee6f5167126d66b217a00afedf1068ec2fb15e7ab22d8b',
  result: 'failed',
  error: '0000000000000000fffffffb00000000' } 

The source code for sending the transaction can be found [here](https://github.com/FredericHeem/js-stellar-base/blob/master/test/functional/functional_test.js)

Would it be possible to get a more meaningful error message ?

**Comment by nullstyle** [comment]
I haven't yet found a good way to actually provide a better error message, but let me run an idea I have by you to see what your thoughts are.

The root of the problem is that any given transaction can have 1 **or more** error messages, one for the transaction as a whole, but then also one for each operation contained within it.  In this specific case, for example "0000000000000000fffffffb00000000"  Is a hex-encoded XDR struct `TransactionResult` (as specified [here](https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-transaction.x#L647))  that contains the `TransactionResultCode` of `txBAD_SEQ` and no error message for the operation contained within the transaction because the network didn't even attempt to apply the operations since the sequence number was bad.

Given that reality, IMO the most prudent way to handle errors related to posting a transaction in your own applications is to directly interrogate the XDR struct returned.  The other notion there is that to form a transaction your code most be able to read and write our XDR, and so it should be trivial to interrogate the direct submission result.

---

That said, I recognize now that the current expression of the error is shitty for human consumption.  I always end up writing a little snippet like the following in a ruby console:

``` ruby
Stellar::TransactionResult.from_xdr Stellar::Convert.from_hex "0000000000000000fffffffb00000000"
```

That's not very friendly, IMO.  Here's what I'm thinking about doing to improve it.  I would like to add a summary of the TransactionResultCode and the OperationResultCodes associated like so:

```
{ 
  hash: '22fae4ad6ad65b7a99ee6f5167126d66b217a00afedf1068ec2fb15e7ab22d8b',
  result: 'failed',
  error: '0000000000000000fffffffb00000000',
  result_codes: {
    transaction: 'tx_bad_seq',
  }
}
```

Or in the case of a multi-operation transaction:

```
{ 
  hash: 'some hash here',
  result: 'failed',
  error: 'some hex here',
  result_codes: {
    transaction: 'tx_failed',
    operations: [
      'op_no_account',
      'inflation_not_time'
    ],
  }
}
```

Thoughts?

**Comment by FredericHeem** [comment]
IMHO, the server should decode/decode the XDR and provides a JSON for the various client libraries, the client does not need to know the underlying XDR encoding/decoding, the XDR knowledge should  reside on the server side. 
Regarding the multi operation transaction, how would you like to handle the case when some transactions succeed and other fail ?

**Comment by nullstyle** [comment]
@FredericHeem, IMO, unless we find that the cost of interoperating with XDR directly is cripplng adoption we must push as many people to use client libraries to encode/decode xdr as we can.

The only reliable, secure, and simple way for a given actor to build a transaction with confidence is to encode and sign it themselves.  A 3rd party (such as horizon) could be compromised or dishonest and provide you an XDR structure that does not represent the payment you intended.  You could solve this particular problem in a number of ways, but they are much more complex then simply interacting with a client library that handles the encoding/decoding for you.  I'd be happy to discuss the solutions that I've thought about, and if you can think of any solutions to the problem I'd be excited to hear them.

Given that the only reliable, secure, and simple way to create transactions is to have a client library that interacts with XDR directly, providing interpretations of the response XDR from that transaction does not seem useful enough for the exposure it entails.  I'm trying to minimize our chances for easy mistakes of integration;  For example, I'm trying to avoid situations like the partial payment bug that we and ripple got hit with last year, or having to refer to the "validated" attribute in a `tx` response to know whether or not a transactions actually succeeded or not.

Regarding multi-operation transactions;  There is no case where some operations would fail and others succeed.  A Transaction in the stellar sense is similar to a transaction in the SQL database sense;  All operations contained within the transaction either succeed or fail as an atomic unit.

**Comment by FredericHeem** [comment]
Thanks a lot for these comments, for now, we can stick to encore/decode on the client side.
