### ISSUE TITLE
Cannot get the transaction by its hash when the transaction fails

### ISSUE THREAD

**Issue by FredericHeem** [stellar/go-horizon#65]
When a transaction fails, for instance when the offer in under funded or the reserve is to too low for changing trust, getting the transaction by its hash return a 404. The only way to find out what's happened is to dig into the _txhistory_ table of the _stellar_ db and decode the _txresult_.

**Comment by nullstyle** [comment]
@FredericHeem This is by design, but also exposes where we haven't yet finished implementing the whole of the API.  This History portions of the horizon api (of which the "Transaction by Hash" endpoint is a member of) only deals in successful transactions.   By ensuring this, we don't run the risk of someone falsely assuming that because `/transactions/SOME_HASH` returns a 200 response that the transaction was successful.  

When the API is complete, making a POST to /transactions will not respond until we have a definitive answer from the network about whether or not the transaction was successful or not.  In the case of a closed connection prior to receiving a response, you would simply re-submit the same exact transaction again and horizon will continue where it left off, returning a response when consensus is complete (or immediately if consensus completed while you were disconnected).

**Comment by FredericHeem** [comment]
Right now, how can we find out when a transaction fails and how do we retrieve the error message ? This is absolutely necessary for any kind of stellar app.

**Comment by nullstyle** [comment]
@FredericHeem I completely realize it is necessary to build any kind of stellar app.  This is one of several reasons why horizon has not had a launch.  We are still pre-alpha.

At present, instead of polling for status on `GET /transactions/HASH`, poll on `POST /transactions` until it responds with a body with the `result` attribute set to something other than "received".  It's not ideal, but I plan on working things out prior to launch so that the whole cycle is cleaner.

**Comment by FredericHeem** [comment]
I am still not convinced  why transactions ended with errors cannot be accessed by its hash. 
Getting a transaction status with an HTTP POST is really weird and non standard. The usage of an HTTP POST is to creates a resource and modifies the server state, HTTP GET is read only, it doesn't modify the server state.

**Comment by nullstyle** [comment]
The reason why I segregate failed transactions from successful, finished transactions is the same reason why the "validated" flag or the partial payment system in the old stellar network were bad ideas:  It adds additional required verification steps for clients, leaving room for misinterpretation of the worst kind in a payment system: false positives payments.  I'm willing to live with a little bit of weirdness if it means the api has fewer possibilities to expose that kind of failure to clients.  Both the justcoin hack and the transaction malleability bug in bitcoin from back in the day are instances of this kind of failure, as some examples about how disastrous a false positive payment can be.  We already have several examples of million's of dollars worth of cryptocurrency pilfered due to these kinds of bugs.

Remember, when the API is feature complete, you'll only be POSTing to "check status" when you get disconnected from the initial submission prior to consensus happening.  In that case, simply posting the transaction again is the most efficient way to check status and retry if necessary.

**Comment by FredericHeem** [comment]
An HTTP POST is not designed to check the status of a resource, it should return immediately with the hash and not waiting synchronously for the reply which can never arrived for a various number of reasons. The api  GET /transactions/<hash>  could be called anytime after the transaction has been created. Knowing the state of a transaction and find out eventual error messages is not an option.
The malleability bug and the partial payment flag vulnerability has little or none in common with this API design discussion.

**Comment by nullstyle** [comment]
> it should return immediately with the hash and not waiting synchronously for the reply

I disagree. We are optimizing this API for understandability, and a synchronous process is almost always going to be simpler to understand and integrate with than an asynchronous process. If you disagree, I’m happy to discuss further.  IMO, an async submission process is only beneficial for efficiency, which is why I plan on allowing an asynchronous submission flag for clients that need to optimize for throughput;  This is something that we will definitely enable in the near future; it’s only absent now because the code is pre-alpha. 

> reply which can never arrived for a various number of reasons

This is exactly why the POST model is better. In the case of ambiguity (connection timeout, server crash, client crash, etc) you can simply POST the transaction again and use the response of the second request as canon.  Idempotency is a powerful tool in HTTP APIs.

> The api GET /transactions/ could be called anytime after the transaction has been created. Knowing the state of a transaction and find out eventual error messages is not an option.

I don't understand what you're trying to express here. Could you please rephrase?

> The malleability bug and the partial payment flag vulnerability has little or none in common with this API design discussion.

I disagree.  Can you explain why you think it has little or none in common?  To me, these bugs were due to a design flaw that made misinterpretation likely.

I think we might be talking about different things, since it feels like your counter-arguments don’t really address what I’m saying. Please let me know if you’d like additional clarification about the POST model we’ll be implementing in the near future.
