### ISSUE TITLE
orderbook in 2 queries

### ISSUE THREAD

**Issue by FredericHeem** [stellar/go-horizon#67]
In _query_order_book_summary.go_, getting the order book is in 2 phases, first the bid, then the ask.
getting the bid and ask array must be done in the same query, otherwise, under heavy load, one might get a bid than is greater than the ask.

**Comment by nullstyle** [comment]
I'm open to integrating a PR that makes this change, but I'm not concerned about the badness of the behavior you describe, so this is pretty low on my personal priority list.  I'm definitely open to be convinced that this is a bigger issue than it appears to me though.  Let me explain why I don't think this is a big deal:

A well-behaved client must deal with the fact that any offer data returned from these endpoints could be obsolete since the network is continually advancing based upon the passage of time.  Given that, we cannot provide any data consistency guarantees to clients that are performing multi-request interactions (such as viewing an orderbook then submitting an offer to trade in response to the data).  To me, that means that the only real scenario where we could provide a fully consistent snapshot would be within the span of a single http request, as you mention in this report. So what sort of errors would occur when you have an orderbook summary that spans a ledger close?  All I can think of is that the spread could be lie, or even negative, as you mention.  While that's not good, I personally don't think it's a huge deal.

**Comment by FredericHeem** [comment]
Getting an order book with the best bid higher than the best ask is really awkward. 
From a performance point of view, using one sql request instead of 2 is also much faster.

**Comment by jedmccaleb** [comment]
Wouldn't you fetch the current orderbook and then listen to updates to the orderbook after that?

**Comment by jedmccaleb** [comment]
Yeah that is true. I think we will do it that way at some point but want to get all the other horizon features in first.

**Comment by nullstyle** [comment]
Fixed in https://github.com/stellar/go-horizon/pull/74
